# DAY 32
## NumPy Data types

In [6]:
import numpy as np

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## List vs Numpy Arrays

In [8]:
py_list = [1,2,3]
print("pylist *2",py_list*2)
np_arr = np.array([1,2,3])
print("np_arr *2",np_arr*2)

pylist *2 [1, 2, 3, 1, 2, 3]
np_arr *2 [2 4 6]


In [9]:
import time
start = time.time()
py_list2 = [i*2 for i in range(10000000)]
print("time:",time.time()-start)

time: 0.9456565380096436


In [10]:
import time
start = time.time()
py_list2 = [i*2 for i in range(10000000)]
print("time:",time.time()-start)

time: 0.9387099742889404


## Creating arrays from scratch


In [11]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
full = np.full((2,3),7)
print(full)

[[7 7 7]
 [7 7 7]]


In [14]:
random = np.random.random((2,3))
print(random)

[[0.04895628 0.98821181 0.13338042]
 [0.98645398 0.4028552  0.04024613]]


In [15]:
Sequence = np.arange(10,21,2)
print(Sequence)

[10 12 14 16 18 20]


## vector, Matrix and Tensor

In [16]:
vector = np.array([1,2,3])
print(vector)

[1 2 3]


In [17]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [18]:
tensor = [
      [[1,2],[3,4]],
      [[5,6],[7,8]]
          ]
print(tensor)

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


## Array Props

In [19]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("shape:",arr.shape)
print("size:",arr.size)
print("dtype:",arr.dtype	)
print("ndim:",arr.ndim)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
size: 6
dtype: int64
ndim: 2


In [20]:
arr = np.arange(1,11)
print(arr)
print("shape:",arr.shape)

[ 1  2  3  4  5  6  7  8  9 10]
shape: (10,)


In [21]:
#reshape
arr2 = arr.reshape(2,5)
print(arr2)
print("shape:",arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
shape: (2, 5)


In [22]:
#flattened
arr3 = arr2.flatten()
print(arr3)
print("shape:",arr3.shape)

[ 1  2  3  4  5  6  7  8  9 10]
shape: (10,)


In [23]:
#reveled
arr4 = arr2.ravel()
print(arr4)
print("shape:",arr4.shape)

[ 1  2  3  4  5  6  7  8  9 10]
shape: (10,)


In [24]:
#Transpose
arr5 = arr2.transpose()
print(arr5)
print("shape:",arr5.shape)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
shape: (5, 2)
